# Generated by Django 4.2 on 2023-04-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True)),
                ('is_group', models.BooleanField(default=False)),
                ('send_lesson', models.BooleanField(default=False)),
                ('last_sent', models.DateField(blank=True, null=True)),
                ('last_lesson_sent', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
