# Generated by Django 4.2 on 2023-05-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_calendar',
            field=models.BooleanField(default=True),
        ),
    ]
