# Generated by Django 4.2 on 2024-06-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_chat_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='username',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
